app = "realona-exchange"

[build]
  [build.args]
    NODE_ENV = "production"

[env]
  PORT = "5000"

[http_service]
  internal_port = 5000
  force_https = true

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[deploy]
  strategy = "rolling"
  min_elapsed = "5s"