import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import listingsRouter from "./listings";
import tradesRouter from "./trades";
import chatRouter from "./chat";
import depositsRouter from "./deposits";
import withdrawalsRouter from "./withdrawals";
import reportsRouter from "./reports";
import adminRouter from "./admin";
import webhooksRouter from "./webhooks";
import storageRouter from "./storage";
import offersRouter from "./offers";
import kycRouter from "./kyc";
import notificationsRouter from "./notifications";
import announcementsRouter from "./announcements";
import giveawaysRouter from "./giveaways";
import leaderboardRouter from "./leaderboard";
import wishlistRouter from "./wishlist";
import purchasesRouter from "./purchases";
import tradeFeedRouter from "./trade-feed";
import platformReviewsRouter from "./platform-reviews";
import sellerAnalyticsRouter from "./seller-analytics";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(listingsRouter);
router.use(tradeFeedRouter);
router.use(tradesRouter);
router.use(chatRouter);
router.use(depositsRouter);
router.use(withdrawalsRouter);
router.use(reportsRouter);
router.use(adminRouter);
router.use(webhooksRouter);
router.use(storageRouter);
router.use(offersRouter);
router.use(kycRouter);
router.use(notificationsRouter);
router.use(announcementsRouter);
router.use(giveawaysRouter);
router.use(leaderboardRouter);
router.use(wishlistRouter);
router.use(purchasesRouter);
router.use(platformReviewsRouter);
router.use(sellerAnalyticsRouter);

export default router;
